version: '3.7'

services: 

    influxdb:
        image: influxdb
        restart: unless-stopped
        ports: 
            - 8086:8086
        volumes:
            - influxdb-data:/var/lib/influxdb

    grafana:
        image: grafana/grafana:6.7.1
        restart: unless-stopped
        ports:
            - 3010:3000
        volumes:
            - grafana-data:/var/lib/grafana

volumes:
    influxdb-data:
    grafana-data:
    