version: '3.7'

services: 

    telegraf:
        build:
            context: .
        environment: 
            - "HOST_PROC=/hostfs/proc"
            - "HOST_MOUNT_PREFIX=/hostfs"
        volumes: 
            - /:/hostfs/:ro
            - /var/run/docker.sock:/var/run/docker.sock
