version: '3.7'

services: 

    telegraf:
        build:
            context: .
        restart: unless-stopped
        environment: 
            - "HOST_PROC=/hostfs/proc"
            - "HOST_MOUNT_PREFIX=/hostfs"
            - "PARENT_HOSTNAME=${HOSTNAME}"
        volumes: 
            - /:/hostfs/:ro
            - /var/run/docker.sock:/var/run/docker.sock
